name: stegano
base: core24
adopt-info: stegano
summary: Image and Audio Steganography
description: |
  A cross-platform command line tool for steganography, focused on performance and simplicity.

grade: stable
confinement: strict

architectures:
  - build-on: amd64
    build-for: arm64

parts:
  stegano:
    plugin: rust
    source: .
    source-subdir: crates/stegano-cli
    override-pull: |
      craftctl default
      craftctl set version="$(git describe --tags)"

apps:
  stegano:
    command: bin/stegano
    plugs:
      - home
